version: '3'

volumes:
  postgres:

networks:
  lumia-network:

services:
  backend:
    networks:
      - lumia-network
    depends_on:
      - postgres
      - ml
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: unless-stopped

  ml:
    networks:
      - lumia-network
    build:
      dockerfile: Dockerfile
      context: ./ml
    volumes:
      - ./ml/models:/app/models
    restart: unless-stopped

  postgres:
    networks:
      - lumia-network
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql
    env_file:
      - .env

